apiVersion: v1
kind: Pod
metadata:
  name: test-multi-1
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: busybox-container
      image: busybox:latest
      command: ['sh', '-c', 'while true; do echo "Hello from BusyBox"; sleep 3600; done']
  nodeSelector:
    targetid: w1
